imx-pico: Always use the NXP bootloader when using the NXP BSP
Freescale/meta-freescale-3rdparty pull request #122
Opened 2021-01-31 13:19 UTC by maximdeclercq

The NXP BSP should always use u-boot-imx. This should make NXP distros buildable on PICO boards. 
Related pull-request: Freescale/meta-freescale#626.

Signed-off-by: Maxim De Clercq <maximdeclercq00@gmail.com>

2021-01-31 15:14 UTC, otavio requested changes
I am fine with the changes, but the commit log must be improved. You are changing multiple boards and not all are the i.MX PICO ones. So please rework it and also mention all the boards being changed.

2021-01-31 15:24 UTC, otavio commented
In fact, the first review is indeed wrong. For `u-boot-imx` specific you should use the `fsl` distros instead.

2021-01-31 15:24 UTC, closed without merging

2021-03-19 13:01 UTC, maximdeclercq commented
This merge request should resolve this issue when building the `fsl` distros.

```
ERROR: Nothing RPROVIDES 'u-boot-fslc' (but /work/sources/core/meta/recipes-core/packagegroups/packagegroup-core-boot.bb RDEPENDS on or otherwise requires it)
u-boot-fslc was skipped: PREFERRED_PROVIDER_virtual/bootloader set to u-boot-imx, not u-boot-fslc
```

The value of `PREFERRED_PROVIDER_virtual/bootloader` is set [here](https://github.com/Freescale/meta-freescale/blob/dunfell/conf/machine/include/imx-base.inc#L30).
Which is set to `IMX_DEFAULT_BOOTLOADER` defined [here](https://github.com/Freescale/meta-freescale-distro/blob/master/conf/distro/include/fsl-base.inc#L15).

2021-03-19 13:20 UTC, maximdeclercq commented
Maybe we should add `IMX_DEFAULT_BOOTLOADER` instead of `u-boot-fslc`?

2021-03-19 13:29 UTC, otavio commented
The only u-boot we tested for pico is u-boot-fslc. It should work for both Linux kernels.

2021-03-19 13:35 UTC, maximdeclercq commented
So I am supposed to override `IMX_DEFAULT_BOOTLOADER` to `u-boot-fslc` even though I am using the `fsl` distro?

2021-03-19 13:42 UTC, otavio commented
for pico, we ought to force it to u-boot-fslc or it'll fail.

2021-03-19 13:56 UTC, maximdeclercq commented
Ah ok, thanks. Shouldn't we fix `PREFERRED_PROVIDER_virtual/bootloader` then?

2021-03-19 14:00 UTC, maximdeclercq commented
I have updated the PR. I guess that should fix it?

2021-03-19 14:03 UTC, maximdeclercq commented
I guess this should fix it? https://github.com/Freescale/meta-freescale-3rdparty/pull/134