Fix nitrogen8 boards
Freescale/meta-freescale-3rdparty pull request #206
Opened 2022-03-09 17:20 UTC by Ossanes

This PR is an improved version of PR #205

-Fixes errors due to new BSP overrides syntax;
-Drop unnecessary code.

2022-03-09 18:53 UTC, otavio approved these changes

2022-03-09 18:53 UTC, otavio commented
@gibsson could you review this?

2022-03-09 19:29 UTC, gibsson requested changes
Why not do that also for all nitrogen (6/7 included)?

2022-03-09 19:51 UTC, Ossanes commented
@gibsson Because nitrogen 6/7 doesn't have overrides on `WKS_FILE_DEPENDS`. Also, in my tests, I could see that no other conf/recipe is adding `e2fsprogs-native` and `bmap-tools-native` to the variable `WKS_FILE_DEPENDS` in nitrogen 6/7, so it must be kept.

2022-03-09 20:01 UTC, gibsson commented
What about this:
https://github.com/Freescale/meta-freescale-3rdparty/blob/master/conf/machine/nitrogen6x.conf#L65
=> shouldn't all configs look like the same as nitrogen8*

2022-03-10 12:48 UTC, gibsson approved these changes

2022-03-10 12:48 UTC, gibsson approved these changes

2022-03-10 12:55 UTC, otavio approved these changes

2022-03-10 12:55 UTC, merged